name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build-Server
      run: cargo build --bin frps_demo --verbose
    - name: Build-Client
      run: cargo build --bin frpc_demo --verbose 
    - name: Run tests
      run: cargo test --verbose
